trainer:
  logger:
    class_path: lightning.pytorch.loggers.CometLogger
    init_args:
      api_key: 96fJNEQDL2NV21l19g3XKHI8G
      save_dir: /gemini/output
      experiment_name: lightning_logs
      project_name: MSCG_Rx50
  enable_checkpointing: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        dirpath: /gemini/output/models
        filename: "{epoch:02d}-{loss:.3f}-{aux_loss:.3f}-{val_loss:.3f}-{acc:.3f}-{miou:.3f}-{f1score:.3f}"
  devices: 1
  max_epochs: 50
  fast_dev_run: False
  log_every_n_steps: 50
  accelerator: gpu

model:
  class_path: libs.lightning.AgricultureSegmentClass
  init_args:
    model_name: MSCG_Rx50
    num_classes: 7
    use_lr_scheduler: True
data:
  class_path: libs.lightning.AgricultureDataClass
  init_args:
    dataset_root: /gemini/Agriculture-Vision
    data_name: Agriculture
    batch_size: 32
    num_workers: 4
#ckpt_path: /gemini/output/models/
