trainer:
  logger: true
  enable_checkpointing: true
  limit_train_batches: 100
  limit_val_batches: 100
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        dirpath: ./output/models
        filename: "{epoch:02d}-{loss:.3f}-{aux_loss:.3f}-{val_loss:.3f}-{acc:.3f}-{miou:.3f}-{f1score:.3f}"
  devices: 1
  max_epochs: 10
  fast_dev_run: False
  log_every_n_steps: 50
  accelerator: gpu

model:
  class_path: libs.lightning.AgricultureSegmentClass
  init_args:
    model_name: MSCG_Rx50
    num_classes: 7
data:
  class_path: libs.lightning.AgricultureDataClass
  init_args:
    dataset_root: D:/Agriculture-Vision
    data_name: Agriculture
    batch_size: 10
    num_workers: 4
ckpt_path: null
